# Generated by Django 2.2.7 on 2020-04-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20181114_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('payday',), 'verbose_name': '付款记录', 'verbose_name_plural': '付款记录'},
        ),
        migrations.AddField(
            model_name='payment',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='增值税额'),
        ),
    ]
