# Generated by Django 2.2.7 on 2020-04-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_auto_20200421_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='stamp_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='印花税金额'),
        ),
    ]
